### ISSUE TITLE
bug: synchronization between two track animations

### ISSUE THREAD

**Issue by magland** [magland/spikesortingview#114]
This one doesn't seem to sync (click the sync-to-global option for both):
https://www.figurl.org/f?v=gs://figurl/spikesortingview-8&d=sha1://10b8c748ed20237abf7f43de742dcc325ad66a12&label=&s={}

And this one seems to be sync'd even when the sync-to-global option is off for both:
https://www.figurl.org/f?v=gs://figurl/spikesortingview-8&d=sha1://4d67715f9bf5e102aab3769886a56e63519c2319&label=&s={}

**Comment by jsoules** [comment]
Interesting.

In the first case, I expect they aren't syncing because the time scales are different--all the time values on the right-hand side are much lower than the left-hand side, so syncing just puts the right-hand side one out of its defined range.

For the second one, not sure why they're syncing when they haven't been requested to. I'll look into that.

**Comment by jsoules** [comment]
Upon further investigation, this is happening because the global syncing of the current timepoint is automatic; you can't turn it off. :)

The tooltip on the sync button says "Sync playback bar to global time range"--this refers to syncing the timespan that's visible in the playback bar to the timespan that's visible in a (potentially zoomed-in) timeseries plot. If global sync is off, the playback bar can be zoomed to show whatever span of the recording you wish, independently of the zoom state of other synced timeseries plots; if global sync is on, then the playback bar will cover only the span of time that's visible in the timeseries plots.

This corresponds to setting the `visibleTimeStartSeconds` and `visibleTimeEndSeconds` properties of the contexual `RecordingSelection` state.

There is a separate sync that takes place that ensures the currently visible frame of animation playback is the same as the global focus time, if any (also from the contextual `RecordingSelection` state, it's the `focusTimeSeconds` property). However, that isn't governed by any settings; it just happens.

If desired, we could allow desyncing of individual animations' playback from the global focus state. I'll open a ticket for that over on the [figurl-franklab-views](https://github.com/magland/figurl-franklab-views) project and we can chat about how to prioritize it.
