### ISSUE TITLE
request for metric with multiple values, one per unit

### ISSUE THREAD

**Issue by lfrank** [magland/spikesortingview#48]
During curation we often want to be able to compare units based on some metric (e.g. waveform similarity). To so do, it would be ideal if we could send in a list of values for each unit corresponding to the computed similarity (or other metric) to all other units. This could of course be sent in as a square matrix as well. 

We would then want to be able to select a unit and sort the other units by the metric in relation to that unit so we could identify potential merge pairs, etc.

**Comment by jsoules** [comment]
Interesting idea, and I can see the utility.

How essential to this functionality would it be to have this as part of the same units table used for everything else? There's a bit of trickiness with how we would represent non-string data types, but that could be massaged; the bigger issue I see is that expanding the existing units table to handle tabular data would introduce a lot of complication to the interface (both for the user and internally).

Essentially you're saying, let's add a new custom metric whose data is, for every unit i of the n units, a labeled set of values for the j != i unis in n. (Maybe that's symmetric, maybe not, doesn't really matter.) To sort that, we need a mechanism to identify the fixed side of the comparison, so that we know we're sorting the rest of the rows according to Unit 4's similarity value, etc. Basically an interface that both allows you to select the privileged unit, as well as communicate which unit is currently privileged, without making the regular operation awkward or confusing.

Let's chat about this some more.

**Comment by lfrank** [comment]
I don’t think this needs to be part of the same table; if there were a separate comparisons table with a unit for each row (as currently implemented) and perhaps paired values (metric and unit_id for that metric) for each column, then if one could sort by a column and select units that way, that would work.

On Apr 28, 2022, at 7:06 AM, Jeff Soules ***@***.******@***.***>> wrote:

This Message Is From an External Sender
This message came from outside your organization.


Interesting idea, and I can see the utility.

How essential to this functionality would it be to have this as part of the same units table used for everything else? There's a bit of trickiness with how we would represent non-string data types, but that could be massaged; the bigger issue I see is that expanding the existing units table to handle tabular data would introduce a lot of complication to the interface (both for the user and internally).

Essentially you're saying, let's add a new custom metric whose data is, for every unit i of the n units, a labeled set of values for the j != i unis in n. (Maybe that's symmetric, maybe not, doesn't really matter.) To sort that, we need a mechanism to identify the fixed side of the comparison, so that we know we're sorting the rest of the rows according to Unit 4's similarity value, etc. Basically an interface that both allows you to select the privileged unit, as well as communicate which unit is currently privileged, without making the regular operation awkward or confusing.

Let's chat about this some more.

**Comment by magland** [comment]
This is being addressed in the similarity matrix view, already implemented. Try that first and then open a new issue for further functionality requests.

Closing
