### ISSUE TITLE
y-axis ticks: need more space for tick value readouts in position plot, possibly other plots

### ISSUE THREAD

**Issue by jsoules** [magland/spikesortingview#90]
They're currently getting cut off.

**Comment by edeno** [comment]
Could we bump this one to high priority?

**Comment by magland** [comment]
This is addressed to some degree in PR #120.
There I allocated more space (40 pixels) to the left margin.
I also removed the dependency of the left margin on timeseriesLayoutOpts in order to guarantee that all timeseries plots line up consistently. I think this is more important than minimizing the margins.

However, this is just a temporary solution. We need to figure out how to set the left margin sensibly so that it accommodates the tick labels (variable width) and is consistent between views.

**Comment by magland** [comment]
@edeno I am closing this for now, but let me know if you encounter problems, and we'll create a new issue.
